name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci

    # Add a step to install VitePress if it's not included in your dependencies
    - name: Install VitePress
      run: npm install vitepress --save-dev

    # Build the VitePress documentation
    - name: Build VitePress
      run: npx vitepress build # Assuming your VitePress files are in the `docs` directory

    # Run tests if you have any (optional)
    # - run: npm test
